runtime: go
api_version: go1
service: speechtest

handlers:
- url: /
  script: _go_app
- url: /savescore
  script: _go_app
- url: /getReadings
  script: _go_app
- url: /saveReadings
  script: _go_app
- url: /admin
  script: _go_app
- url: /resources
  static_dir: resources